In [22]:
from database import get_engine
from queries import(
    faturamento_total, faturamento_desempenho,
    produto_top, top_produtos, top_pais, top_moedas,
    margem_mes, margem_desempenho, margem_categoria
)
from sqlalchemy import text
import pandas as pd

engine = get_engine()

mes = '2019-12'

In [2]:
from data_import import importar_csv_para_banco

importar_csv_para_banco()

CSVs importados com sucesso!
Products
Sales
Customers
Data_Dictionary
Exchange_Rates
Stores

In [9]:
df = pd.read_sql(faturamento_total(), engine)
display(df)
with open('../queries/01_faturamento_total.sql', 'w') as f:
    f.write(faturamento_total())

,qtde_pedidos,qtde_vendas,faturamento_bruto,custo_total,faturamento_liquido,ticket_medio
0,26326,197757.0,55755479.59,23092791.21,32662688.38,2117.89

In [10]:
df = pd.read_sql(faturamento_desempenho(), engine)
display(df)
with open('../queries/02_faturamento_desempenho.sql', 'w') as f:
    f.write(faturamento_desempenho())

       data  faturamento_bruto  custo_total  faturamento_liquido  media_mes
0   2019-12         2477295.85   1041747.61           1435548.24  526817.55
1   2020-02         2227379.57    915930.34           1311449.23  526817.55
2   2019-02         2102862.57    864969.31           1237893.26  526817.55
3   2018-12         2082206.04    878645.82           1203560.22  526817.55
4   2020-01         2068951.12    859831.73           1209119.39  526817.55
..      ...                ...          ...                  ...        ...
57  2020-04          217642.10     89612.56            128029.54  526817.55
58  2019-04          149892.71     61420.26             88472.45  526817.55
59  2016-04          110591.63     44360.44             66231.19  526817.55
60  2018-04           70627.54     29796.14             40831.40  526817.55
61  2017-04           58580.07     23515.35             35064.72  526817.55

[62 rows x 5 columns]

In [23]:
df = pd.read_sql(produto_top(mes), engine)
display(df)
with open('../queries/03_produto_top.sql', 'w') as f:
    f.write(produto_top(mes))

                                     produtos  faturamento_liquido
0  Adventure Works Desktop PC2.33 XD233 Black             22678.25

In [24]:
df = pd.read_sql(top_produtos(mes), engine)
display(df)
with open('../queries/04_top_produtos.sql', 'w') as f:
    f.write(top_produtos(mes))

                                      produtos  faturamento_liquido
0   Adventure Works Desktop PC2.33 XD233 Black             22678.25
1               WWI Desktop PC2.33 X2330 Black             17206.56
2              WWI Projector 1080p LCD86 White             16880.82
3    Fabrikam Refrigerator 24.7CuFt X9800 Blue             14978.39
4  Adventure Works Desktop PC2.33 XD233 Silver             14254.90

In [25]:
df = pd.read_sql(top_pais(mes), engine)
display(df)
with open('../queries/05_top_pais.sql', 'w') as f:
    f.write(top_pais(mes))

     compras_pais  faturamento_liquido
0   United States            742893.25
1  United Kingdom            176667.53
2          Canada            160691.75
3         Germany            141209.95
4       Australia             59871.99

In [26]:
df = pd.read_sql(top_moedas(mes), engine)
display(df)
with open('../queries/06_top_moedas.sql', 'w') as f:
    f.write(top_moedas(mes))

  moeda_utilizada  faturamento_bruto
0             USD         1282986.92
1             EUR          514715.76
2             GBP          302859.76
3             CAD          272280.21
4             AUD          104453.20

In [20]:
mes = '2019-12'
df = pd.read_sql(margem_mes(mes), engine)
display(df)
with open('../queries/07_margem_mes.sql', 'w') as f:
    f.write(margem_mes(mes))

      data  margem
0  2019-12   57.95

In [14]:
df = pd.read_sql(margem_desempenho(), engine)
display(df)
with open('../queries/08_margem_desempenho.sql', 'w') as f:
    f.write(margem_desempenho())

       data  margem
0   2017-07   58.53
1   2017-10   57.82
2   2016-07   59.21
3   2019-01   58.57
4   2018-03   59.29
..      ...     ...
57  2016-06   56.74
58  2016-11   59.95
59  2017-04   59.86
60  2016-02   59.67
61  2018-12   57.80

[62 rows x 2 columns]

In [27]:
df = pd.read_sql(margem_categoria(mes), engine)
display(df)
with open('../queries/09_margem_categoria.sql', 'w') as f:
    f.write(margem_categoria(mes))

                       categoria  margem
0  Music, Movies and Audio Books   60.86
1         Cameras and camcorders   60.23
2                      Computers   57.89
3                          Audio   57.29
4                   TV and Video   57.12
5                    Cell phones   56.91
6                Home Appliances   56.90
7                 Games and Toys   53.60