In [6]:
from database import get_engine
from queries import (
    total_vendas, vendas_mes, crescimento, 
    consumo, campanha, pais, tempo_relacionamento,
    faixa_etaria, reclamacao
)
from sqlalchemy import text
import pandas as pd

engine = get_engine()

mes='2012-12'

In [18]:
df1 = pd.read_csv('../raw/marketing_data.csv')
df2 = pd.read_csv('../raw/marketing_data_dictionary.csv')

df1.to_sql('marketing_data', engine, if_exists='replace', index=False)
df2.to_sql('marketing_data_dictionary', engine, if_exists='replace', index=False)

print("Todos os CSVs foram importados!")

with engine.connect() as conn:
    resultado = conn.execute(text("select table_name from information_schema.tables where table_schema = 'public'"))
    for linha in resultado:
        print(linha[0])

Todos os CSVs foram importados!
marketing_data
marketing_data_dictionary

In [3]:
df = pd.read_sql(total_vendas(), engine)
display(df)
with open('../queries/01_total_vendas.sql', 'w') as f:
    f.write(total_vendas())

   compras_desconto  compras_web  compras_catalogo  compras_loja    total
0            5208.0       9150.0            5963.0       12970.0  33291.0

In [5]:
df = pd.read_sql(crescimento(), engine)
display(df)
with open('../queries/02_crescimento.sql', 'w') as f:
    f.write(crescimento())

,mes_compras,compras_desconto,compras_web,compras_catalogo,compras_loja,total_vendas,variacao_percentual,media_mes,classificação
0,2012-07,5.0,15.0,9.0,16.0,45.0,NaN,1387.0,Abaixo da Média
1,2012-08,367.0,571.0,367.0,721.0,2026.0,4402.22,1387.0,Acima da Média
2,2012-09,303.0,493.0,352.0,664.0,1812.0,-10.56,1387.0,Acima da Média
3,2012-10,306.0,433.0,268.0,591.0,1598.0,-11.81,1387.0,Acima da Média
4,2012-11,279.0,501.0,305.0,637.0,1722.0,7.76,1387.0,Acima da Média
5,2012-12,190.0,321.0,185.0,420.0,1116.0,-35.19,1387.0,Abaixo da Média
6,2013-01,296.0,515.0,309.0,669.0,1789.0,60.30,1387.0,Acima da Média
7,2013-02,267.0,492.0,298.0,614.0,1671.0,-6.60,1387.0,Acima da Média
8,2013-03,297.0,482.0,257.0,631.0,1667.0,-0.24,1387.0,Acima da Média
9,2013-04,195.0,382.0,286.0,506.0,1369.0,-17.88,1387.0,Abaixo da Média
10,2013-05,232.0,406.0,320.0,635.0,1593.0,16.36,1387.0,Acima da Média
11,2013-06,222.0,372.0,236.0,516.0,1346.0,-15.51,1387.0,Abaixo da Média
12,2013-07,220.0,362.0,210.0,566.0,1358.0,0.89,1387.0,Abaixo da Média
13,2013-08,213.0,413.0,243.0,609.0,1478.0,8.84,1387.0,Acima da Média
14,2013-09,186.0,341.0,222.0,487.0,1236.0,-16.37,1387.0,Abaixo da Média
15,2013-10,249.0,478.0,317.0,660.0,1704.0,37.86,1387.0,Acima da Média
16,2013-11,176.0,365.0,273.0,580.0,1394.0,-18.19,1387.0,Acima da Média
17,2013-12,160.0,329.0,235.0,519.0,1243.0,-10.83,1387.0,Abaixo da Média
18,2014-01,192.0,335.0,245.0,534.0,1306.0,5.07,1387.0,Abaixo da Média
19,2014-02,133.0,236.0,174.0,429.0,972.0,-25.57,1387.0,Abaixo da Média
20,2014-03,201.0,354.0,222.0,529.0,1306.0,34.36,1387.0,Abaixo da Média
21,2014-04,150.0,301.0,204.0,499.0,1154.0,-11.64,1387.0,Abaixo da Média
22,2014-05,213.0,409.0,277.0,576.0,1475.0,27.82,1387.0,Acima da Média
23,2014-06,156.0,244.0,149.0,362.0,911.0,-38.24,1387.0,Abaixo da Média

In [5]:
df = pd.read_sql(consumo(), engine)
display(df)
with open('../queries/03_consumo.sql', 'w') as f:
    f.write(consumo())

     vinhos   frutas     carne    peixe    doces     ouro
0  680816.0  58917.0  373968.0  84057.0  60621.0  98609.0

In [4]:
df = pd.read_sql(campanha(mes), engine)
display(df)
with open('../queries/04_campanha.sql', 'w') as f:
    f.write(campanha(mes))

,primeira_campanha,segunda_campanha,terceira_campanha,quarta_campanha,quinta_campanha
0,4.0,3.0,8.0,9.0,4.0

In [5]:
df = pd.read_sql(pais(mes), engine)
display(df)
with open('../queries/05_pais.sql', 'w') as f:
    f.write(pais(mes))

  localidade_cliente  gasto_total
0              Spain      46748.0
1       Saudi Arabia      15569.0
2             Canada       7591.0
3                USA       5999.0
4              India       5984.0
5          Australia       5721.0
6            Germany       4434.0

In [12]:
df = pd.read_sql(tempo_relacionamento(), engine)
display(df)
with open('../queries/06_tempo_relacionamento.sql', 'w') as f:
    f.write(tempo_relacionamento())

   qtde_clientes tempo_relacionamento
0           1156       Menos de 1 ano
1           1084        Mais de 1 ano

In [13]:
df = pd.read_sql(faixa_etaria(), engine)
display(df)
with open('../queries/07_faixa_etaria.sql', 'w') as f:
    f.write(faixa_etaria())

   qtde_clientes faixa_etaria  porcentagem_total
0           2112      Adultos              94.29
1             66       Idosos               2.95
2             62       Jovens               2.77

In [3]:
df = pd.read_sql(reclamacao(), engine)
display(df)
with open('../queries/08_reclamacao.sql', 'w') as f:
    f.write(reclamacao())

   qtde_clientes      reclamacao  porcentagem_total
0           2219  Não reclamaram              99.06
1             21      Reclamaram               0.94