# Limpeza dos dados Restaurant Ratings

In [1]:
import pandas as pd 
import numpy as np 

consumer_preferences = pd.read_csv("../data/raw/consumer_preferences.csv")
consumers = pd.read_csv("../data/raw/consumers.csv")
ratings = pd.read_csv("../data/raw/ratings.csv")
restaurant_cuisines = pd.read_csv("../data/raw/restaurant_cuisines.csv")
restaurants = pd.read_csv("../data/raw/restaurants.csv")

### Verificando se existem nulos

In [2]:
consumer_preferences.isnull().sum()

Consumer_ID          0
Preferred_Cuisine    0
dtype: int64

In [3]:
consumers.isnull().sum()

Consumer_ID               0
City                      0
State                     0
Country                   0
Latitude                  0
Longitude                 0
Smoker                    3
Drink_Level               0
Transportation_Method     7
Marital_Status            4
Children                 11
Age                       0
Occupation                7
Budget                    7
dtype: int64

In [4]:
ratings.isnull().sum()

Consumer_ID       0
Restaurant_ID     0
Overall_Rating    0
Food_Rating       0
Service_Rating    0
dtype: int64

In [5]:
restaurant_cuisines.isnull().sum()

Restaurant_ID    0
Cuisine          0
dtype: int64

In [6]:
restaurants.isnull().sum()

Restaurant_ID       0
Name                0
City                0
State               0
Country             0
Zip_Code           74
Latitude            0
Longitude           0
Alcohol_Service    87
Smoking_Allowed     0
Price               0
Franchise           0
Area                0
Parking            65
dtype: int64

### Verificando duplicatas

In [7]:
consumer_preferences.duplicated().sum()

np.int64(2)

In [8]:
consumers.duplicated().sum()

np.int64(0)

In [9]:
ratings.duplicated().sum()

np.int64(0)

In [10]:
restaurant_cuisines.duplicated().sum()

np.int64(0)

In [11]:
restaurants.duplicated().sum()

np.int64(0)

### Verificando os tipos de dados dos arquivos

In [12]:
consumer_preferences.info()

<class 'pandas.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Consumer_ID        330 non-null    str
 1   Preferred_Cuisine  330 non-null    str
dtypes: str(2)
memory usage: 9.4 KB

In [13]:
consumers.info()

<class 'pandas.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Consumer_ID            138 non-null    str
 1   City                   138 non-null    str
 2   State                  138 non-null    str
 3   Country                138 non-null    str
 4   Latitude               138 non-null    float64
 5   Longitude              138 non-null    float64
 6   Smoker                 135 non-null    str
 7   Drink_Level            138 non-null    str
 8   Transportation_Method  131 non-null    str
 9   Marital_Status         134 non-null    str
 10  Children               127 non-null    str
 11  Age                    138 non-null    int64
 12  Occupation             131 non-null    str
 13  Budget                 131 non-null    str
dtypes: float64(2), int64(1), str(11)
memory usage: 26.7 KB

In [14]:
ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 1161 entries, 0 to 1160
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Consumer_ID     1161 non-null   str
 1   Restaurant_ID   1161 non-null   int64
 2   Overall_Rating  1161 non-null   int64
 3   Food_Rating     1161 non-null   int64
 4   Service_Rating  1161 non-null   int64
dtypes: int64(4), str(1)
memory usage: 51.1 KB

In [15]:
restaurant_cuisines.info()

<class 'pandas.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Restaurant_ID  112 non-null    int64
 1   Cuisine        112 non-null    str
dtypes: int64(1), str(1)
memory usage: 2.7 KB

In [16]:
restaurants.info()

<class 'pandas.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Restaurant_ID    130 non-null    int64
 1   Name             130 non-null    str
 2   City             130 non-null    str
 3   State            130 non-null    str
 4   Country          130 non-null    str
 5   Zip_Code         56 non-null     float64
 6   Latitude         130 non-null    float64
 7   Longitude        130 non-null    float64
 8   Alcohol_Service  43 non-null     str
 9   Smoking_Allowed  130 non-null    str
 10  Price            130 non-null    str
 11  Franchise        130 non-null    str
 12  Area             130 non-null    str
 13  Parking          65 non-null     str
dtypes: float64(3), int64(1), str(10)
memory usage: 23.8 KB

### Verificando as colunas com nulos

In [17]:
consumers[
    ['Smoker', 'Transportation_Method', 'Marital_Status', 'Children', 'Occupation', 'Budget']
    ].head(5)

  Smoker Transportation_Method Marital_Status     Children Occupation  Budget
0     No               On Foot         Single  Independent    Student  Medium
1     No                Public         Single  Independent    Student     Low
2     No                Public         Single  Independent    Student     Low
3     No                Public         Single  Independent   Employed  Medium
4     No                Public         Single  Independent    Student  Medium

In [18]:
restaurants[
    ['Zip_Code', 'Alcohol_Service', 'Parking']
    ].head(5)

   Zip_Code Alcohol_Service Parking
0       NaN             NaN  Public
1       NaN             NaN     NaN
2       NaN             NaN     NaN
3       NaN             NaN     Yes
4   62000.0             NaN     NaN

### Cruzando as informações das tabelas

In [19]:
nulos_restaurant_ratings = (
    ratings
    .merge(consumers, on="Consumer_ID", how="left")
    .merge(restaurant_cuisines, on="Restaurant_ID", how="left")
    .merge(restaurants, on="Restaurant_ID", how="left")
    .merge(consumer_preferences, on="Consumer_ID", how="left")
    .reset_index()
    [['Smoker', 'Transportation_Method', 'Marital_Status', 'Children', 'Occupation', 'Budget', 'Zip_Code', 'Alcohol_Service', 'Parking']]
    .head(5)
)
display(nulos_restaurant_ratings)

,Smoker,Transportation_Method,Marital_Status,Children,Occupation,Budget,Zip_Code,Alcohol_Service,Parking
0,No,Public,Married,Kids,Student,Medium,78000.0,NaN,Public
1,No,Public,Married,Kids,Student,Medium,78000.0,NaN,NaN
2,No,Public,Married,Kids,Student,Medium,78280.0,NaN,NaN
3,No,Public,Married,Kids,Student,Medium,78310.0,NaN,NaN
4,No,Public,Single,Independent,Student,Low,NaN,Full Bar,Yes

### Iniciando o tratamento dos dados

In [20]:
consumer_preferences = consumer_preferences.drop_duplicates()

restaurants['Zip_Code'] = restaurants['Zip_Code'].fillna(restaurants['Zip_Code'].median())
restaurants['Alcohol_Service'] = restaurants['Alcohol_Service'].fillna('Não Informado')
restaurants['Parking'] = restaurants['Parking'].fillna('Não Informado')

consumers['Smoker'] = consumers['Smoker'].fillna('Não Informado')
consumers['Transportation_Method'] = consumers['Transportation_Method'].fillna('Não Informado')
consumers['Marital_Status'] = consumers['Marital_Status'].fillna('Não Informado')
consumers['Children'] = consumers['Children'].fillna('Não Informado')
consumers['Occupation'] = consumers['Occupation'].fillna('Não Informado')
consumers['Budget'] = consumers['Budget'].fillna('Não Informado')

In [21]:
consumer_preferences.duplicated().sum()

np.int64(0)

In [22]:
restaurants.isnull().sum()

Restaurant_ID      0
Name               0
City               0
State              0
Country            0
Zip_Code           0
Latitude           0
Longitude          0
Alcohol_Service    0
Smoking_Allowed    0
Price              0
Franchise          0
Area               0
Parking            0
dtype: int64

In [23]:
consumers.isnull().sum()

Consumer_ID              0
City                     0
State                    0
Country                  0
Latitude                 0
Longitude                0
Smoker                   0
Drink_Level              0
Transportation_Method    0
Marital_Status           0
Children                 0
Age                      0
Occupation               0
Budget                   0
dtype: int64

### Exportando os arquivos tratados

In [25]:
consumer_preferences.to_csv('../data/processed/consumer_preferences.csv', index=False)
consumers.to_csv('../data/processed/consumers.csv', index=False)
ratings.to_csv('../data/processed/ratings.csv', index=False)
restaurant_cuisines.to_csv('../data/processed/restaurant_cuisines.csv', index=False)
restaurants.to_csv('../data/processed/restaurants.csv', index=False)