In [1]:
from sqlalchemy import text
from database import get_engine
from queries import (
    volume_total_saldo, clientes_mais_produtos, 
    faixa_etaria_clientes, tempo_relacionamento, 
    categoria_renda, porcentagem_cancelamento
)
import pandas as pd

engine = get_engine()

In [8]:
df1 = pd.read_csv('../raw/bank_churn_data_dictionary.csv')
df2 = pd.read_csv('../raw/bank_churn.csv')

df1.to_sql('bank_churn_data_dictionary', engine, if_exists='replace', index=False)
df2.to_sql('bank_churn', engine, if_exists='replace', index=False)

print('Todas as tabelas foram importadas!')

Todas as tabelas foram importadas!

In [2]:
with engine.connect() as conn:
    resultado = conn.execute(text("select table_name from information_schema.tables where table_schema = 'public'"))
    for linha in resultado:
        print(linha[0])

bank_churn_data_dictionary
bank_churn

In [17]:
df = pd.read_sql(volume_total_saldo(), engine)
display(df)

with open('../queries/01_volume_total_saldo.sql', 'w') as f:
    f.write(volume_total_saldo())

  pais_do_cliente  clientes_ativos  total_depositos
0          France             2591     1.575602e+08
1         Germany             1248     1.496035e+08
2           Spain             1312     8.367055e+07

In [18]:
df = pd.read_sql(clientes_mais_produtos(), engine)
display(df)

with open('../queries/02_clientes_mais_produtos.sql', 'w') as f:
    f.write(clientes_mais_produtos())

   clientes  qtde_produtos  porcentagem_do_total
0        29              4                  0.56
1       113              3                  2.19
2      2446              2                 47.49
3      2563              1                 49.76

In [19]:
df = pd.read_sql(faixa_etaria_clientes(), engine)
display(df)

with open('../queries/03_faixa_etaria_clientes.sql', 'w') as f:
    f.write(faixa_etaria_clientes())

   qtde_clientes faixa_etaria  porcentagem_do_total
0           4749      Adultos                  92.2
1            232       Idosos                   4.5
2            170       Jovens                   3.3

In [20]:
df = pd.read_sql(tempo_relacionamento(), engine)
display(df)

with open('../queries/04_tempo_relacionamento.sql', 'w') as f:
    f.write(tempo_relacionamento())

   qtde_clientes tempo_relacionamento  porcentagem_do_total
0           3279       Mais de 3 anos                 63.66
1           1653        De 1 a 3 anos                 32.09
2            219            Até 1 ano                  4.25

In [21]:
df = pd.read_sql(categoria_renda(), engine)
display(df)

with open('../queries/05_categoria_renda.sql', 'w') as f:
    f.write(categoria_renda())

   qtde_clientes categoria_renda  porcentagem_do_total
0           1323      Alta Renda                 25.68
1           1312     Média Renda                 25.47
2           1272     Baixa Renda                 24.69
3           1244           Elite                 24.15

In [22]:
df = pd.read_sql(porcentagem_cancelamento(), engine)
display(df)

with open('../queries/06_porcentagem_cancelamento.sql', 'w') as f:
    f.write(porcentagem_cancelamento())

   qtde_clientes conta_cancelada  porcentagem_do_total
0           7963             Não                 79.63
1           2037             Sim                 20.37